# Generated by Django 4.2.4 on 2023-10-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_price_currency_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
